### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by FarshidKeivanian** [Avisek20/ecm#1]
Dataset folder was not available

**Comment by Avisek20** [comment]
For the MATLAB implementation, the datasets can be kept in a 'datasets' folder in the main directory. The name of the datasets need to be saved in 'list_datasets.txt'.

**Comment by Avisek20** [comment]
For the MATLAB implementation, the datasets can be kept in a 'datasets' folder in the main directory. The name of the datasets need to be saved in 'list_datasets.txt'.
